# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
        language_version: python3
    -   id: end-of-file-fixer
        language_version: python3
    -   id: check-yaml
        language_version: python3
    -   id: check-added-large-files
        language_version: python3
    -   id: check-byte-order-marker
        language_version: python3
    -   id: check-case-conflict
        language_version: python3
    -   id: check-json
        language_version: python3
    -   id: mixed-line-ending
        language_version: python3

-   repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    -   id: black
        language_version: python3

-   repo: https://github.com/asottile/blacken-docs
    rev: v1.12.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black]
        language_version: python3

-   repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        language_version: python3
        args: ["--profile", "black", "--filter-files"]

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      language_version: python3

-   repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
    -   id: pyupgrade
        language_version: python3
        args: [--py37-plus]
