# Read the Docs configuration file for Sphinx projects
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/conf.py
