import pytest
from civic_scraper.platforms import LegistarSite


legistar_sites = [
    {'site': 'http://kpb.legistar.com/Calendar.aspx',
    'timezone': 'US/Alaska',
    },
    {'site': 'http://matanuska.legistar.com/Calendar.aspx',
    'timezone': 'US/Alaska',
    },
    {'site': 'http://npfmc.legistar.com/Calendar.aspx',
    'timezone': 'US/Alaska',
    },
    {'site': 'http://petersburg.legistar.com/Calendar.aspx',
    'timezone': 'US/Alaska',
    },
    {'site': 'http://sitka.legistar.com/Calendar.aspx',
    'timezone': 'US/Alaska',
    },
    {'site': 'http://valdez.legistar.com/Calendar.aspx',
    'timezone': 'US/Alaska',
    },
    {'site': 'http://baldwincountyal.legistar.com/Calendar.aspx',
    'timezone': 'US/Central',
    },
    {'site': 'http://cityoffoley.legistar.com/Calendar.aspx',
    'timezone': 'US/Central',
    },
    {'site': 'http://accessfayetteville.legistar.com/Calendar.aspx',
    'timezone': 'US/Central',
    },
    {'site': 'http://jonesboro.legistar.com/Calendar.aspx',
    'timezone': 'US/Central',
    },
    {'site': 'http://apachejunction.legistar.com/Calendar.aspx',
    'timezone': 'US/Arizona',
    },
    {'site': 'http://goodyear.legistar.com/Calendar.aspx',
    'timezone': 'US/Arizona',
    },
    {'site': 'http://lakehavasucity.legistar.com/Calendar.aspx',
    'timezone': 'US/Arizona',
    },
    {'site': 'http://maricopa.legistar.com/Calendar.aspx',
    'timezone': 'US/Arizona',
    },
    {'site': 'http://mesa.legistar.com/Calendar.aspx',
    'timezone': 'US/Arizona',
    },
    {'site': 'http://paradisevalleyaz.legistar.com/Calendar.aspx',
    'timezone': 'US/Arizona',
    },
    {'site': 'http://phoenix.legistar.com/Calendar.aspx',
    'timezone': 'US/Arizona',
    },
    {'site': 'http://pima.legistar.com/Calendar.aspx',
    'timezone': 'US/Arizona',
    },
    {'site': 'http://yuma-az.legistar.com/Calendar.apx',
    'timezone': 'US/Arizona',
    },
    {'site': 'http://alameda.legistar.com/Calendar.aspx',
    'timezone': 'US/Pacific',
    },
    {'site': 'http://actransit.legistar.com/Calendar.aspx',
    'timezone': 'US/Pacific',
    },
    {'site': 'http://burlingameca.legistar.com/Calendar.aspx',
    'timezone': 'US/Pacific',
    },
    {'site': 'http://carson.legistar.com/Calendar.aspx',
    'timezone': 'US/Pacific',
    },
    {'site': 'http://cathedralcity.legistar.com/Calendar.aspx',
    'timezone': 'US/Pacific',
    },
    {'site': 'http://chulavista.legistar.com/Calendar.aspx',
    'timezone': 'US/Pacific',
    },
    {'site': 'http://cityofcommerce.legistar.com/Calendar.aspx',
    'timezone': 'US/Pacific',
    },
    {'site': 'http://corona.legistar.com/Calendar.aspx',
    'timezone': 'US/Pacific',
    },
    {'site': 'http://culver-city.legistar.com/Calendar.apx',
    'timezone': 'US/Pacific',
    },
    {'site': 'http://cupertino.legistar.com/Calendar.aspx',
    'timezone': 'US/Pacific',
    },
    {'site': 'http://eldorado.legistar.com/Calendar.aspx',
    'timezone': 'US/Pacific',
    },
]

def test_integration():
    for obj in legistar_sites:
        print('\n\n')
        print(obj['site'])
        scraper = LegistarSite(obj['site'], timezone=obj['timezone'])
        data = scraper.scrape()
        assert len(data) > 10
