import pytest


legistar_sites = [
    {'site': 'kpb.legistar.com/Calendar.aspx',
    'timezone': 'US/Alaska',
    },
    {'site': 'matanuska.legistar.com/Calendar.aspx',
    'timezone': 'US/Alaska',
    },
    {'site': 'npfmc.legistar.com/Calendar.aspx',
    'timezone': 'US/Alaska',
    },
    {'site': 'petersburg.legistar.com/Calendar.aspx',
    'timezone': 'US/Alaska',
    },
    {'site': 'sitka.legistar.com/Calendar.aspx',
    'timezone': 'US/Alaska',
    },
    {'site': 'valdez.legistar.com/Calendar.aspx',
    'timezone': 'US/Alaska',
    },
    {'site': 'baldwincountyal.legistar.com/Calendar.aspx',
    'timezone': 'US/Central',
    },
    {'site': 'cityoffoley.legistar.com/Calendar.aspx',
    'timezone': 'US/Central',
    },
    {'site': 'accessfayetteville.legistar.com/Calendar.aspx',
    'timezone': 'US/Central',
    },
    {'site': 'jonesboro.legistar.com/Calendar.aspx',
    'timezone': 'US/Central',
    },
    {'site': 'apachejunction.legistar.com/Calendar.aspx',
    'timezone': 'US/Arizona',
    },
    {'site': 'goodyear.legistar.com/Calendar.aspx',
    'timezone': 'US/Arizona',
    },
    {'site': 'lakehavasucity.legistar.com/Calendar.aspx',
    'timezone': 'US/Arizona',
    },
    {'site': 'maricopa.legistar.com/Calendar.aspx',
    'timezone': 'US/Arizona',
    },
    {'site': 'mesa.legistar.com/Calendar.aspx',
    'timezone': 'US/Arizona',
    },
    {'site': 'paradisevalleyaz.legistar.com/Calendar.aspx',
    'timezone': 'US/Arizona',
    },
    {'site': 'phoenix.legistar.com/Calendar.aspx',
    'timezone': 'US/Arizona',
    },
    {'site': 'pima.legistar.com/Calendar.aspx',
    'timezone': 'US/Arizona',
    },
    {'site': 'yuma-az.legistar.com/Calendar.apx',
    'timezone': 'US/Arizona',
    },
    {'site': 'alameda.legistar.com/Calendar.aspx',
    'timezone': 'US/Pacific',
    },
    {'site': 'actransit.legistar.com/Calendar.aspx',
    'timezone': 'US/Pacific',
    },
    {'site': 'burlingameca.legistar.com/Calendar.aspx',
    'timezone': 'US/Pacific',
    },
    {'site': 'carson.legistar.com/Calendar.aspx',
    'timezone': 'US/Pacific',
    },
    {'site': 'cathedralcity.legistar.com/Calendar.aspx',
    'timezone': 'US/Pacific',
    },
    {'site': 'chulavista.legistar.com/Calendar.aspx',
    'timezone': 'US/Pacific',
    },
    {'site': 'cityofcommerce.legistar.com/Calendar.aspx',
    'timezone': 'US/Pacific',
    },
    {'site': 'corona.legistar.com/Calendar.aspx',
    'timezone': 'US/Pacific',
    },
    {'site': 'culver-city.legistar.com/Calendar.apx',
    'timezone': 'US/Pacific',
    },
    {'site': 'cupertino.legistar.com/Calendar.aspx',
    'timezone': 'US/Pacific',
    },
    {'site': 'eldorado.legistar.com/Calendar.aspx',
    'timezone': 'US/Pacific',
    },
]

def test_integration():
    # use state info to get timezone
    # use below loop to instantiate scrapers
    for site, config in [list of (site, config)]:
        scraper = LegistarSite(site, config)
        data = scraper.scrape()
        assert len(data) > 10
